/**
 * 代发申请相关
 */
export const APPLY_LIST_START = "APPLY_LIST_START";
export const APPLY_LIST_DONE = "APPLY_LIST_DONE";
export const GET_APPLY_LIST = "GET_APPLY_LIST";
export const DETAIL_LIST_START = "DETAIL_LIST_START";
export const DETAIL_LIST_DONE = "DETAIL_LIST_DONE";
export const SHOW_DETAIL_MODAL = "SHOW_DETAIL_MODAL";
export const HIDE_DETAIL_MODAL = "HIDE_DETAIL_MODAL";
export const GET_DETAIL_LIST = "GET_DETAIL_LIST";
export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_DONE = "UPLOAD_DONE";
    
