export const SHOW_FILE_MODAL = "SHOW_FILE_MODAL";
export const HIDE_FILE_MODAL = "HIDE_FILE_MODAL";
export const GET_DATASWITCH_LIST = "GET_DATASWITCH_LIST";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";