export const SHOW_LEADINGFILE_MODAL = "SHOW_LEADINGFILE_MODAL";
export const HIDE_LEADINGFILE_MODAL = "HIDE_LEADINGFILE_MODAL";

export const SHOW_UPLOAD_MODAL = "SHOW_UPLOAD_MODAL";
export const HIDE_UPLOAD_MODAL = "HIDE_UPLOAD_MODAL";

export const SHOW_DETAIL_MODAL = "SHOW_DETAIL_MODAL";
export const HIDE_DETAIL_MODAL = "HIDE_DETAIL_MODAL";