
export const RECEIPT_QUERY_LIST = "RECEIPT_QUERY_LIST";
export const HIDE_RECEIPT_MODAL = "HIDE_RECEIPT_MODAL";
export const SHOW_RECEIPT_MODAL = "SHOW_RECEIPT_MODAL";
export const COMPANY_LIST = "COMPANY_LIST";
export const RATEANDEARN_LIST = "RATEANDEARN_LIST";
export const CALCULATE = "CALCULATE";
export const CALCULATE_START = "CALCULATE_START";