/**
 * 系统管理
 */

//系统参数列表查询
export const PARAMETER_LIST_START = "PARAMETER_LIST_START";
export const PARAMETER_LIST_DONE = "PARAMETER_LIST_DONE";
export const GET_PARAMETER_LIST = "GET_PARAMETER_LIST";
export const SHOW_SAVE_PARAMETER = "SHOW_SAVE_PARAMETER";
export const HIDE_SAVE_PARAMETER = "HIDE_SAVE_PARAMETER";
export const TEMP_LIST_START = "TEMP_LIST_START";
export const TEMP_LIST_DONE = "TEMP_LIST_DONE";
export const GET_TEMP_LIST = "GET_TEMP_LIST";
export const LOG_LIST = "LOG_LIST";
export const LOG_LIST_START = "LOG_LIST_START";
export const LOG_LIST_DONE = "LOG_LIST_DONE";
export const ROLE_LIST = "ROLE_LIST";
export const SHOW_SAVE_TEMP = "SHOW_SAVE_TEMP";
export const HIDE_SAVE_TEMP = "HIDE_SAVE_TEMP";
export const SET_RESETTEMP_TRUE = "SET_RESETTEMP_TRUE";
export const SET_RESETTEMP_FALSE = "SET_RESETTEMP_FALSE";
export const GET_CORP_LIST = "GET_CORP_LIST";
export const USERINFO_LIST_START = "USERINFO_LIST_START";
export const USERINFO_LIST_DONE = "USERINFO_LIST_DONE";
export const GET_USERINFO_LIST = "GET_USERINFO_LIST";
export const SHOW_ADDACCESS_MODAL = "SHOW_ADDACCESS_MODAL";
export const HIDE_ADDACCESS_MODAL = "HIDE_ADDACCESS_MODAL"
export const SHOW_SAVE_USERINFO = "SHOW_SAVE_USERINFO";
export const HIDE_SAVE_USERINFO = "HIDE_SAVE_USERINFO";
export const SET_RESETUSERINFO_TRUE = "SET_RESETUSERINFO_TRUE";
export const SET_RESETUSERINFO_FALSE = "SET_RESETUSERINFO_FALSE";
export const SHOW_RELOADPWD = "SHOW_RELOADPWD";
export const HIDE_RELOADPWD = "HIDE_RELOADPWD";
export const SET_RELOADPWD_TRUE = "SET_RELOADPWD_TRUE";
export const SET_RELOADPWD_FALSE = "SET_RELOADPWD_FALSE";
